### ISSUE TITLE
outqueue_bytes is less than the frame we just dequeued

### ISSUE THREAD

**Issue by Echsecutor** [devguardio/carrier#14]
I just tried the carrier on my laptop via a mobile internet connection. During the very simple first tests (http://book.devguard.io/quickstart/discovery.html) the `carrier 0.10.1-9-g537d710-dirty-DlRJeeQ44h` itself reports a "BUG". ;)

Terminal 1:
'''
$ carrier publish
[INFO  carrier::endpoint] carrier identity: oXFGmSydejDvvMJkp1XZQrE1781b9r9CWJdus2e1i4ysjm5 version: 0.10.1-9-g537d710-dirty-DlRJeeQ44h 
[INFO  carrier::endpoint] attempting udp connection with 5.9.122.66:8443
[INFO  carrier::endpoint] attempting udp connection with 5.9.156.3:8443
[INFO  carrier::endpoint] attempting udp connection with 88.198.32.218:8443
[INFO  carrier::endpoint] established connection with broker oWSs6CqSoPT8nU9QUiMC1L6n88h8sxFJG2iYn13qs45Hvfd
[INFO  carrier::endpoint] pubres: [:status = 200, ]
[INFO  carrier::publisher] incomming oXFGmSydejDvvMJkp1XZQrE1781b9r9CWJdus2e1i4ysjm5
[INFO  carrier::publisher::shell] shell stream constructed
[ERROR carrier::publisher::shell] EIO: I/O error
[INFO  carrier::publisher::shell] shell stream deconstructed
[WARN  carrier::channel] BUG outqueue_bytes is less than the frame we just dequeued
[WARN  carrier::channel] [8600874234052071436::oWSs6CqSoPT8nU9QUiMC1L6n88h8sxFJG2iYn13qs45Hvfd] retransmission timeout (retransmit 1 frames, in flight: 0) at 145497
[WARN  carrier::channel] [oXFGmSydejDvvMJkp1XZQrE1781b9r9CWJdus2e1i4ysjm5::1321139338533813004] retransmission timeout (retransmit 1 frames, in flight: 0) at 93500
[WARN  carrier::channel] [oXFGmSydejDvvMJkp1XZQrE1781b9r9CWJdus2e1i4ysjm5::1321139338533813004] retransmission timeout (retransmit 1 frames, in flight: 0) at 93900
[WARN  carrier::channel] [oXFGmSydejDvvMJkp1XZQrE1781b9r9CWJdus2e1i4ysjm5::1321139338533813004] retransmission timeout (retransmit 1 frames, in flight: 0) at 94701
[INFO  carrier::publisher] incomming oXFGmSydejDvvMJkp1XZQrE1781b9r9CWJdus2e1i4ysjm5
[WARN  carrier::channel] [oXFGmSydejDvvMJkp1XZQrE1781b9r9CWJdus2e1i4ysjm5::1321139338533813004] retransmission timeout (retransmit 1 frames, in flight: 0) at 96301
[WARN  carrier::channel] BUG outqueue_bytes is less than the frame we just dequeued
[WARN  carrier::channel] [oXFGmSydejDvvMJkp1XZQrE1781b9r9CWJdus2e1i4ysjm5::1321139338533813004] retransmission timeout (retransmit 1 frames, in flight: 0) at 99504
[WARN  carrier::channel] [oXFGmSydejDvvMJkp1XZQrE1781b9r9CWJdus2e1i4ysjm5::1321139338533813004] connection is unrecoverable
[WARN  carrier::channel] BUG outqueue_bytes is less than the frame we just dequeued
'''

Terminal 2:
'''
$ carrier discovery oXFGmSydejDvvMJkp1XZQrE1781b9r9CWJdus2e1i4ysjm5
[INFO  carrier::endpoint] carrier identity: oXFGmSydejDvvMJkp1XZQrE1781b9r9CWJdus2e1i4ysjm5 version: 0.10.1-9-g537d710-dirty-DlRJeeQ44h 
[INFO  carrier::endpoint] attempting udp connection with 88.198.32.218:8443
[INFO  carrier::endpoint] attempting udp connection with 5.9.156.3:8443
[INFO  carrier::endpoint] attempting udp connection with 5.9.122.66:8443
[INFO  carrier::endpoint] attempting tcp connection with 88.198.32.218:123
[INFO  carrier::endpoint] established connection with broker oWSs6CqSoPT8nU9QUiMC1L6n88h8sxFJG2iYn13qs45Hvfd
[:status = 200, ]
DiscoveryResponse {
    carrier_revision: 82,
    carrier_build_id: "0.10.1-9-g537d710-dirty-DlRJeeQ44h",
    application: "carrier-cli",
    application_version: "0.10.1-9-g537d710-dirty-DlRJeeQ44h",
    paths: [
        "/v0/shell",
        "/v0/tcp",
        "/v2/carrier.sysinfo.v1/sysinfo",
        "/v0/sft",
    ],
}
'''

**Comment by Echsecutor** [comment]
As you can see, the discovery worked in the end, but maybe you still want to investigate what's going on ;)

**Comment by aep** [comment]
Thank you for your report!

We're aware of the issue.  It only affects traffic counters.
