### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by DBX12** [devguardio/carrier#2]
Hey it's me again,
while testing the previous ticket, I found a bug in the documentation on https://devguard.io/intro.html. It's only marginal but might confuse new users.
After starting up the axiom service (should I call it service?) with the blue shadow address and the green identity in accept, I go to a different machine and should use the green identity.
In fact, I should go to the green-identity-machine and connect to my thing by entering its identity.

Maybe you can color-code the `$` signs as well, to show on which machine we should run the commands.
Again, thx for color-coding the identities and shadow addresses.

**Comment by aep** [comment]
Hi, documentation has improved significantly. Let me know if you have any feedback.
