### ISSUE TITLE
request to open source devguard ring

### ISSUE THREAD

**Issue by yangjungis** [devguardio/carrier#20]
request to open source devguard ring。

**Comment by aep** [comment]
depends on the use case. 

The current system is very specific to our data centers, without any way to configure it for other network infrastructure. Not sure what good that would be for anyone else.

**Comment by yangjungis** [comment]
Inspired by this project, it is planned to design a centralized network management system for peripheral wireless network equipment (router, AP) configuration management, performance monitoring and device access terminal.Wireless network devices wrap the existing P2P encryption communication protocol on SNMP.How is the protocol specification between Carrier and Devguard Ring and UDP NAT P2P punched in this project solved?

**Comment by aep** [comment]
Yeah that's something devguard does for about 10k openwrt devices in the wild. It's free to use, but if you want to build your own competing product, i'd recommend looking at this article to get started:

https://bford.info/pub/net/p2pnat/

This is essentially where the basic algorithms come from. Also lots of learnings from STUN and http3.

particularly you want to read https://tools.ietf.org/html/draft-ietf-quic-recovery-31

Additionally the broker does some fairly boring proxying to get through hostile networks. It's not proprietary or hard to replicate. The real challenge is doing it cost effective. Each carrier channel has a unique 64bit identifier it can use to get routed along the edges of the ring. You'll have to find your own particular algorithm that matches your datacenter infrastructure. We have several distributed datacenters in europe that route like 10G/s using fpgas. Might sell the hardware at some point if anyone cares.
