### ISSUE TITLE
Error while building Rust Api

### ISSUE THREAD

**Issue by Nako11** [devguardio/carrier#21]
Hello,
while building the Rust-High-Level-Api with cargo following error shows up:
error[E0061]: this function takes 4 arguments but 3 arguments were supplied
  --> src/error.rs:26:17
   |
26 |                 err::to_str(self.as_mut_ptr(), s.as_mut_ptr(), s.len());
   |                 ^^^^^^^^^^^ -----------------  --------------  ------- supplied 3 arguments
   |                 |
   |                 expected 4 arguments

error: aborting due to previous error; 6 warnings emitted

I fixed it by replacing the line with the following 
`err::to_str(self.as_mut_ptr(), self.0.len(), s.as_mut_ptr(), s.len());` since i guessed it needs the pointer and the len of the internal byte vector.

Related question: Is the Rust-Api up to date and are there any instructions on how to use it?

**Comment by aep** [comment]
thanks for the report. this is a mismatch between zz versions, should actually have been caught by CI. odd.

**Comment by aep** [comment]
oh to answer your second question, no. the rust api is purely a legacy bridge to old code that is still using rust. You'll have a bad time trying to use it for new projects. For server side use the nodejs api, for embedded use zetz.

**Comment by Nako11** [comment]
Thanks for your answer. I'll close.
