### ISSUE TITLE
Dead connection during ota

### ISSUE THREAD

**Issue by schphil** [devguardio/carrier#22]
Hi, 

while trying to update openwrt firmware over ota, I getting the following error:

[WRN] carrier::pq BUG: bucket 21 has f->typ == 0
[WRN] carrier::pq BUG: bucket 22 has f->typ == 0
[WRN] carrier::pq BUG: bucket 23 has f->typ == 0
[WRN] carrier::pq BUG: bucket 24 has f->typ == 0
[WRN] carrier::pq BUG: bucket 25 has f->typ == 0
[WRN] carrier::pq BUG: bucket 26 has f->typ == 0
[WRN] carrier::pq BUG: bucket 27 has f->typ == 0
[WRN] carrier::pq BUG: bucket 28 has f->typ == 0
[ERR] carrier::channel [11123959467116558162] connection is dead
[WRN] carrier::connect connect closed
channel.go:185: unexpected unlink
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x4713f3a]

runtime stack:
runtime.throw(0x4a024a5, 0x2a)
	/usr/local/Cellar/go/1.15.7_1/libexec/src/runtime/panic.go:1116 +0x72
runtime.sigpanic()
	/usr/local/Cellar/go/1.15.7_1/libexec/src/runtime/signal_unix.go:726 +0x48c

goroutine 1 [syscall]:
runtime.cgocall(0x470e990, 0xc00095da68, 0x0)
	/usr/local/Cellar/go/1.15.7_1/libexec/src/runtime/cgocall.go:133 +0x5b fp=0xc00095da38 sp=0xc00095da00 pc=0x40078fb
github.com/devguardio/carrier/go._Cfunc_io_write_bytes(0x0, 0x10008200, 0xc000836a38, 0xc000836a50, 0x0)
	_cgo_gotypes.go:2694 +0x4d fp=0xc00095da68 sp=0xc00095da38 pc=0x4108c8d
github.com/devguardio/carrier/go.(*Endpoint).Wakeup.func1(0xc000853d40, 0xc000011d20, 0xc000836a38, 0x2, 0x2, 0xc000836a50, 0x40dc3a0)
	/Users/runner/work/carrier/carrier/go/endpoint.go:216 +0x91 fp=0xc00095dab0 sp=0xc00095da68 pc=0x4119751
github.com/devguardio/carrier/go.(*Endpoint).Wakeup(0xc000853d40, 0x0, 0x0)
	/Users/runner/work/carrier/carrier/go/endpoint.go:216 +0xea fp=0xc00095db20 sp=0xc00095dab0 pc=0x4110e0a
github.com/devguardio/carrier/go.(*Stream).SendRaw(0xc00091c3f0, 0xc0008cf000, 0x1f4, 0x1f4, 0x1f4, 0x0)
	/Users/runner/work/carrier/carrier/go/channel.go:379 +0x48 fp=0xc00095dbd0 sp=0xc00095db20 pc=0x410e5a8
github.com/devguardio/carrier/cli/src.init.3.func2(0xc00091a840, 0xc00091c360, 0x3, 0x3)
	/Users/runner/work/carrier/carrier/cli/src/sft.go:152 +0x885 fp=0xc00095dd90 sp=0xc00095dbd0 pc=0x470a085
github.com/spf13/cobra.(*Command).execute(0xc00091a840, 0xc00091c2d0, 0x3, 0x3, 0xc00091a840, 0xc00091c2d0)
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:854 +0x2c2 fp=0xc00095de68 sp=0xc00095dd90 pc=0x41effa2
github.com/spf13/cobra.(*Command).ExecuteC(0x4f9a480, 0xc00081ff60, 0x1, 0x1)
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x375 fp=0xc00095df40 sp=0xc00095de68 pc=0x41f0cd5
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
github.com/devguardio/carrier/cli/src.Main()
	/Users/runner/work/carrier/carrier/cli/src/main.go:48 +0x171 fp=0xc00095df78 sp=0xc00095df40 pc=0x4705151
main.main()
	/Users/runner/work/carrier/carrier/cli/main.go:10 +0x25 fp=0xc00095df88 sp=0xc00095df78 pc=0x470dac5
runtime.main()
	/usr/local/Cellar/go/1.15.7_1/libexec/src/runtime/proc.go:204 +0x209 fp=0xc00095dfe0 sp=0xc00095df88 pc=0x403bdc9
runtime.goexit()
	/usr/local/Cellar/go/1.15.7_1/libexec/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc00095dfe8 sp=0xc00095dfe0 pc=0x406e901

goroutine 22 [chan receive]:
github.com/devguardio/carrier/go.(*Channel).ded(0xc00086e560)
	/Users/runner/work/carrier/carrier/go/channel.go:56 +0x52
github.com/devguardio/carrier/go.Connect.func3.1(0xc000853d40, 0xc00086e560)
	/Users/runner/work/carrier/carrier/go/channel.go:145 +0x4b
github.com/devguardio/carrier/go.Connect.func3(0xc000853d40, 0xc00086e560, 0xc000010800)
	/Users/runner/work/carrier/carrier/go/channel.go:186 +0x419
created by github.com/devguardio/carrier/go.Connect
	/Users/runner/work/carrier/carrier/go/channel.go:140 +0x52c

goroutine 24 [select]:
github.com/cheggaaa/pb/v3.(*ProgressBar).writer(0xc000932000, 0xc00003c8a0)
	/Users/runner/go/pkg/mod/github.com/cheggaaa/pb/v3@v3.0.5/pb.go:173 +0xc5
created by github.com/cheggaaa/pb/v3.(*ProgressBar).Start
	/Users/runner/go/pkg/mod/github.com/cheggaaa/pb/v3@v3.0.5/pb.go:167 +0x1e8

Related question:  Is there a limitation on the file size, or am I missing something? Transferring small files (few kb) with " carrier fs push <target> <local-file> <remote-file> [flags]" works. 

Thanks in advance.

**Comment by aep** [comment]
Hi,

this is a very old bug. please update your carrier peers to 0.17

**Comment by schphil** [comment]
thanks for your reply. i'm running carrier version 0.17 on mac os. for the openwrt target I checked out tag 0.17 and did the zz build. I compiled the carrier package with the openwrt toolchain. 

include $(TOPDIR)/rules.mk

PKG_NAME:=carrier
PKG_VERSION:=0.17
PKG_RELEASE:=1

include $(INCLUDE_DIR)/package.mk

define Package/carrier
  SECTION:=network
  CATEGORY:=Devguard
  TITLE:=devguard carrier
  DEPENDS:=+libuci
endef

define Build/Prepare
	mkdir -p $(PKG_BUILD_DIR)
endef


include src/make/carrier_openwrt/Makefile.include


#TARGET_CFLAGS += -ggdb3

TARGET_CFLAGS += -DOPENWRT_BUILD
TARGET_CFLAGS += $(addprefix -I, $(carrier_openwrt_CINCLUDES))

TARGET_LDLAGS += -luci -lpthread

define Build/Compile
	$(foreach src,$(carrier_openwrt_SOURCES),
		$(TARGET_CC) $(TARGET_CFLAGS) -o $(PKG_BUILD_DIR)/$(notdir ${src}).o -c ${src}
	)
	$(TARGET_CC) $(TARGET_LDLAGS) $(PKG_BUILD_DIR)/*.o -o $(PKG_BUILD_DIR)/carrier
endef

define Package/carrier/install
	$(INSTALL_DIR) $(1)/usr/sbin
	$(INSTALL_BIN) $(PKG_BUILD_DIR)/carrier $(1)/usr/sbin/carrier
	$(INSTALL_DIR) $(1)/etc/init.d/
	$(INSTALL_BIN) carrier.init $(1)/etc/init.d/carrier

endef

$(eval $(call BuildPackage,carrier))

outcome on openwrt target:

carrier 0.13 [zz]
devguard carrier is a secure message system for IoT

does usage contains the wrong version ? (https://github.com/devguardio/carrier/blob/master/core/src/openwrt.zz)

is it possible to cross compile it directly?

**Comment by aep** [comment]
Interesting. Haven't seen that in the wild anymore since 0.17. This might be an issue causes by proxy head of line blocking. What's the transfer speed you're getting before unlink? 

Yes the usage string is wrong.

If you have a C cross compiler you can just use the standard CC env variable i.e. 

```
CC=mips-gcc zz build
```

**Comment by schphil** [comment]
I am experiencing the same behavior with updated peers. I also tried diffrent architectures. Same problem. 

Speed is about 8.3 kb/s .

Start log (sender): 

<img width="842" alt="sender_start" src="https://user-images.githubusercontent.com/44805897/116825523-fd1ad800-ab8f-11eb-9bf6-47fe9de95ce5.png">

Dead connection log (sender): 

<img width="833" alt="sender_connection_dead" src="https://user-images.githubusercontent.com/44805897/116825489-dceb1900-ab8f-11eb-87d0-1b49b5e8113a.png">

Log (receiver):

![receiver](https://user-images.githubusercontent.com/44805897/116825561-23d90e80-ab90-11eb-90d7-91ae09880eaa.jpg)

**Comment by schphil** [comment]
when transfer speed is below 5kb/s, file seems to be transferred. the execution of carrier fs ota doesn't exit, though. it keeps on looping warn messages. sysupgrade is not executed on target. 

<img width="1699" alt="Screenshot 2021-05-03 at 16 36 43" src="https://user-images.githubusercontent.com/44805897/116890341-cd221200-ac2d-11eb-9ba4-031e2279f282.png">

**Comment by aep** [comment]
Maybe try downgrading to an earlier version and see if that solves your issue.

like 8b052a6
and also try 0.15.1

**Comment by aep** [comment]
Hi,
carrier1 is no longer supported. please update to carrier3
